# kr210_arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.05
#   kinematics_solver_timeout: 0.05

kr210_arm:
  # 插件库名/类名，格式：<package_name>/<fully_qualified_class_name>
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin  

  # 最多尝试次数（可选，默认 3）  
  kinematics_solver_attempts: 3

  # 搜索分辨率（米），越小越精细但越慢  
  kinematics_solver_search_resolution: 0.01 

  # 单次求解超时时间（秒），可根据实际场景调整  
  kinematics_solver_timeout: 0.05
